#!/usr/bin/env python3
"""
setup_wizard.py — First-run web wizard for deemix-bulk.

Opens http://127.0.0.1:7171 in your default browser and walks through:
  1. Starting the deemix-gui server (auto-detected from the project folder)
  2. Creating / signing in to Deezer + grabbing your ARL session token
  3. Download quality (FLAC / MP3 320) and release types
  4. NAS / SMB destination (optional)
  5. AI artist disambiguation via Ollama (optional)
  6. Building your artists.txt list (type or paste)
  7. Writing .env and artists.txt, then showing the launch commands

Usage:
    python setup_wizard.py
"""

import http.cookiejar
import http.server
import json
import os
import shutil
import subprocess
import sys
import threading
import time
import urllib.request
import webbrowser
from pathlib import Path

# --------------------------------------------------------------------------- #
HOST = "127.0.0.1"
PORT = 7171
DEEMIX_DEFAULT = "http://127.0.0.1:6595"


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def find_deemix_exe():
    for exe in sorted(Path(".").glob("*.exe")):
        n = exe.name.lower()
        if "deemix" in n or "win-x64" in n:
            return str(exe.resolve())
    return None


def deemix_running(server=DEEMIX_DEFAULT):
    try:
        req = urllib.request.Request(f"{server}/api/getSettings",
                                     headers={"User-Agent": "wizard/1"})
        with urllib.request.urlopen(req, timeout=4) as r:
            return r.status == 200
    except Exception:
        return False


def start_deemix_server(exe_path):
    flags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
    subprocess.Popen([exe_path], creationflags=flags,
                     cwd=str(Path(exe_path).parent))


def load_existing_env(path=".env"):
    out = {}
    if not os.path.isfile(path):
        return out
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def load_existing_artists(path="artists.txt"):
    if not os.path.isfile(path):
        return []
    out = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if s and not s.startswith("#"):
                out.append(s)
    return out


def verify_arl(arl, server=DEEMIX_DEFAULT):
    jar = http.cookiejar.CookieJar()
    opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(jar))
    body = json.dumps({"arl": arl, "force": False, "child": 0}).encode()
    req = urllib.request.Request(
        f"{server}/api/loginArl", data=body, method="POST",
        headers={"Content-Type": "application/json", "User-Agent": "wizard/1"})
    with opener.open(req, timeout=15) as r:
        resp = json.loads(r.read().decode())
    if resp.get("status") != 1:
        raise RuntimeError(f"Login failed — check your ARL (status {resp.get('status')})")
    return (resp.get("user") or {}).get("name", "?")


def test_nas(host, share, user, password):
    unc = rf"\\{host}\{share}"
    try:
        subprocess.run(["net", "use", unc, "/delete", "/y"],
                       capture_output=True, timeout=10)
    except subprocess.TimeoutExpired:
        pass
    try:
        r = subprocess.run(["net", "use", unc, password, f"/user:{user}"],
                           capture_output=True, text=True, timeout=20)
    except subprocess.TimeoutExpired:
        raise RuntimeError("Connection timed out — is the host reachable?")
    if r.returncode != 0:
        msg = (r.stderr or r.stdout or "").strip()
        raise RuntimeError(msg or "Connection failed — check credentials")


def write_env(config, path=".env"):
    lines = [
        "# Generated by setup_wizard.py — do NOT commit this file.\n",
        "\n",
        f"DEEMIX_ARL={config.get('DEEMIX_ARL', '')}\n",
        f"DEEMIX_SERVER={config.get('DEEMIX_SERVER', DEEMIX_DEFAULT)}\n",
        f"DEEMIX_QUALITY={config.get('DEEMIX_QUALITY', 'flac')}\n",
        "\n",
    ]
    if config.get("NAS_HOST"):
        lines += [
            f"NAS_HOST={config['NAS_HOST']}\n",
            f"NAS_SHARE={config.get('NAS_SHARE', '')}\n",
            f"NAS_USER={config.get('NAS_USER', '')}\n",
            f"NAS_PASS={config.get('NAS_PASS', '')}\n",
            f"NAS_MUSIC_PATH={config.get('NAS_MUSIC_PATH', 'media/music')}\n",
            "\n",
        ]
    if config.get("OLLAMA_API_KEY"):
        lines += [
            f"OLLAMA_API_KEY={config['OLLAMA_API_KEY']}\n",
            f"OLLAMA_MODEL={config.get('OLLAMA_MODEL', 'gemini-3-flash-preview')}\n",
            "\n",
        ]
    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)


def write_artists(artists, path="artists.txt"):
    if os.path.isfile(path) and not os.path.isfile(path + ".bak"):
        shutil.copy2(path, path + ".bak")
    header = (
        "# One artist per line. Blank lines and lines starting with # are ignored.\n"
        "# Accepts: artist name, Deezer artist ID, or Deezer artist URL.\n"
        "\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        for a in artists:
            if a.strip():
                f.write(a.strip() + "\n")


# --------------------------------------------------------------------------- #
# HTTP handler
# --------------------------------------------------------------------------- #

class WizardHandler(http.server.BaseHTTPRequestHandler):

    def log_message(self, *args):
        pass

    # -- GET ------------------------------------------------------------------

    def do_GET(self):
        if self.path in ("/", "/index.html"):
            body = HTML.encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", len(body))
            self.end_headers()
            self.wfile.write(body)

        elif self.path == "/api/status":
            env = load_existing_env()
            self.send_json({
                "serverRunning": deemix_running(env.get("DEEMIX_SERVER", DEEMIX_DEFAULT)),
                "exePath": find_deemix_exe(),
                "env": env,
                "artists": load_existing_artists(),
            })

        else:
            self.send_error(404)

    # -- POST -----------------------------------------------------------------

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        body = {}
        if length:
            try:
                body = json.loads(self.rfile.read(length).decode())
            except Exception:
                pass

        if self.path == "/api/start-server":
            exe = body.get("exe") or find_deemix_exe()
            if not exe:
                self.send_json({"ok": False,
                                "error": "No deemix .exe found in the project folder."})
                return
            try:
                start_deemix_server(exe)
                server = body.get("server", DEEMIX_DEFAULT)
                for _ in range(20):
                    time.sleep(0.5)
                    if deemix_running(server):
                        self.send_json({"ok": True})
                        return
                self.send_json({"ok": False,
                                "error": "Server started but not responding — try refreshing."})
            except Exception as e:
                self.send_json({"ok": False, "error": str(e)})

        elif self.path == "/api/check-server":
            srv = body.get("server", DEEMIX_DEFAULT)
            self.send_json({"running": deemix_running(srv)})

        elif self.path == "/api/verify-arl":
            try:
                name = verify_arl(body["arl"],
                                  body.get("server", DEEMIX_DEFAULT))
                self.send_json({"ok": True, "name": name})
            except Exception as e:
                self.send_json({"ok": False, "error": str(e)})

        elif self.path == "/api/test-nas":
            try:
                test_nas(body["host"], body["share"],
                         body["user"], body["password"])
                self.send_json({"ok": True})
            except Exception as e:
                self.send_json({"ok": False, "error": str(e)})

        elif self.path == "/api/save":
            try:
                write_env(body.get("config", {}))
                artists = body.get("artists", [])
                if artists:
                    write_artists(artists)
                self.send_json({"ok": True})
            except Exception as e:
                self.send_json({"ok": False, "error": str(e)})

        elif self.path == "/api/shutdown":
            self.send_json({"ok": True})
            threading.Timer(0.4, self.server.shutdown).start()

        else:
            self.send_error(404)

    def send_json(self, data, status=200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", len(body))
        self.end_headers()
        self.wfile.write(body)


# --------------------------------------------------------------------------- #
# Embedded single-page wizard
# --------------------------------------------------------------------------- #

HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>deemix-bulk · Setup</title>
<style>
:root{
  --bg:#0d0d14;--card:#16161f;--card2:#1d1d28;--border:#252535;
  --accent:#818cf8;--accent2:#a78bfa;--adim:rgba(129,140,248,.12);
  --ok:#34d399;--warn:#fbbf24;--err:#f87171;
  --txt:#e2e8f0;--txt2:#94a3b8;--txt3:#475569;
  --r:10px;--tr:.18s ease;
}
*{box-sizing:border-box;margin:0;padding:0}
html,body{height:100%}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
  background:var(--bg);color:var(--txt);display:flex;flex-direction:column;min-height:100vh}

/* ---- header ---- */
header{padding:18px 32px 0;flex-shrink:0}
.hrow{display:flex;align-items:center;gap:12px;margin-bottom:14px}
.logo{font-size:15px;font-weight:700;letter-spacing:.03em;color:var(--accent)}
.logo span{color:var(--txt2);font-weight:400}
.step-label{margin-left:auto;font-size:12px;color:var(--txt3)}
.prog-track{height:3px;background:var(--border);border-radius:2px;overflow:hidden}
.prog-fill{height:100%;background:linear-gradient(90deg,var(--accent),var(--accent2));
  border-radius:2px;transition:width .4s ease;width:0%}

/* ---- main ---- */
main{flex:1;display:flex;align-items:flex-start;justify-content:center;
  padding:28px 16px 110px;overflow-y:auto}
.step{display:none;flex-direction:column;gap:20px;width:100%;max-width:620px}
.step.active{display:flex;animation:fadeUp .22s ease}
@keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}

/* ---- cards ---- */
.card{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:24px}
.card-title{font-size:20px;font-weight:700;margin-bottom:6px}
.card-sub{color:var(--txt2);font-size:14px;line-height:1.6}
h2{font-size:22px;font-weight:700}
h3{font-size:15px;font-weight:600;margin-bottom:8px}
p{color:var(--txt2);font-size:14px;line-height:1.65}

/* ---- form elements ---- */
label{font-size:13px;color:var(--txt2);display:block;margin-bottom:5px}
input[type=text],input[type=password],input[type=url],select,textarea{
  width:100%;background:var(--card2);border:1px solid var(--border);border-radius:6px;
  color:var(--txt);font-size:14px;padding:9px 12px;outline:none;
  font-family:inherit;transition:border-color var(--tr)}
input:focus,select:focus,textarea:focus{border-color:var(--accent)}
textarea{resize:vertical;min-height:220px;font-family:'Cascadia Code','Fira Mono',monospace;
  font-size:13px;line-height:1.55}
.field{display:flex;flex-direction:column;gap:4px}
.row2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.show-hide{position:relative}
.show-hide input{padding-right:44px}
.show-hide .eye{position:absolute;right:10px;top:50%;transform:translateY(-50%);
  background:none;border:none;color:var(--txt3);cursor:pointer;font-size:16px;padding:4px}
.show-hide .eye:hover{color:var(--txt2)}

/* ---- buttons ---- */
button{cursor:pointer;font-family:inherit;border-radius:6px;font-size:14px;
  font-weight:500;transition:all var(--tr);border:none}
.btn-primary{background:var(--accent);color:#fff;padding:10px 22px}
.btn-primary:hover{background:var(--accent2)}
.btn-primary:disabled{opacity:.4;cursor:not-allowed}
.btn-secondary{background:var(--card2);color:var(--txt);border:1px solid var(--border);
  padding:9px 18px}
.btn-secondary:hover{border-color:var(--accent);color:var(--accent)}
.btn-ghost{background:none;color:var(--txt3);padding:8px 14px}
.btn-ghost:hover{color:var(--txt)}
.btn-danger{background:rgba(248,113,113,.12);color:var(--err);
  border:1px solid rgba(248,113,113,.25);padding:9px 18px}
.btn-icon{display:inline-flex;align-items:center;gap:7px}
.full{width:100%}

/* ---- status badges ---- */
.badge{display:inline-flex;align-items:center;gap:6px;padding:5px 12px;
  border-radius:20px;font-size:13px;font-weight:500}
.badge-ok{background:rgba(52,211,153,.12);color:var(--ok);border:1px solid rgba(52,211,153,.2)}
.badge-warn{background:rgba(251,191,36,.1);color:var(--warn);border:1px solid rgba(251,191,36,.2)}
.badge-err{background:rgba(248,113,113,.1);color:var(--err);border:1px solid rgba(248,113,113,.2)}
.dot{width:7px;height:7px;border-radius:50%;background:currentColor;flex-shrink:0}

/* ---- inline feedback ---- */
.feedback{font-size:13px;margin-top:8px;padding:8px 12px;border-radius:6px;display:none}
.feedback.ok{display:block;background:rgba(52,211,153,.1);color:var(--ok)}
.feedback.err{display:block;background:rgba(248,113,113,.1);color:var(--err)}
.feedback.info{display:block;background:var(--adim);color:var(--accent)}

/* ---- instruction steps ---- */
.steps-list{display:flex;flex-direction:column;gap:10px}
.s-item{display:flex;gap:14px;align-items:flex-start}
.s-num{flex-shrink:0;width:26px;height:26px;border-radius:50%;background:var(--adim);
  border:1px solid var(--accent);color:var(--accent);font-size:12px;font-weight:700;
  display:flex;align-items:center;justify-content:center}
.s-text{font-size:14px;color:var(--txt2);line-height:1.6;padding-top:2px}
.s-text a{color:var(--accent);text-decoration:none}
.s-text a:hover{text-decoration:underline}
kbd{background:var(--card2);border:1px solid var(--border);border-radius:4px;
  padding:1px 6px;font-size:12px;color:var(--txt);font-family:inherit}

/* ---- toggle ---- */
.toggle-row{display:flex;align-items:center;gap:12px;padding:14px;
  background:var(--card2);border-radius:8px;cursor:pointer;user-select:none}
.toggle-row .tlabel{flex:1;font-size:14px;font-weight:500}
.toggle-row .tsub{font-size:12px;color:var(--txt3);margin-top:2px}
.toggle{position:relative;width:40px;height:22px;flex-shrink:0}
.toggle input{opacity:0;width:0;height:0;position:absolute}
.tslider{position:absolute;inset:0;background:var(--border);border-radius:11px;
  transition:background var(--tr);cursor:pointer}
.tslider:before{content:'';position:absolute;width:16px;height:16px;
  border-radius:50%;background:#fff;left:3px;top:3px;transition:transform var(--tr)}
.toggle input:checked+.tslider{background:var(--accent)}
.toggle input:checked+.tslider:before{transform:translateX(18px)}
.opt-body{margin-top:16px;display:flex;flex-direction:column;gap:14px}
.opt-body.hidden{display:none}

/* ---- quality selector ---- */
.qual-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.qual-card{border:2px solid var(--border);border-radius:8px;padding:16px;cursor:pointer;
  transition:all var(--tr);position:relative}
.qual-card.selected{border-color:var(--accent);background:var(--adim)}
.qual-card h4{font-size:15px;margin-bottom:4px}
.qual-card p{font-size:12px;color:var(--txt3)}
.qual-card .check{position:absolute;top:10px;right:10px;opacity:0;
  color:var(--accent);font-size:16px;transition:opacity var(--tr)}
.qual-card.selected .check{opacity:1}

/* ---- release type chips ---- */
.chip-row{display:flex;gap:8px;flex-wrap:wrap}
.chip{padding:6px 14px;border-radius:20px;font-size:13px;font-weight:500;cursor:pointer;
  border:1.5px solid var(--border);background:transparent;color:var(--txt2);
  transition:all var(--tr)}
.chip.on{border-color:var(--accent);background:var(--adim);color:var(--accent)}

/* ---- artist area ---- */
.artist-counter{font-size:13px;color:var(--txt3);margin-top:8px;text-align:right}
.artist-tags{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px;max-height:120px;
  overflow-y:auto}
.atag{background:var(--card2);border:1px solid var(--border);border-radius:4px;
  font-size:12px;padding:3px 9px;color:var(--txt2);white-space:nowrap;
  max-width:200px;overflow:hidden;text-overflow:ellipsis}
.dup-warn{background:rgba(251,191,36,.08);border:1px solid rgba(251,191,36,.2);
  border-radius:6px;padding:10px 14px;font-size:13px;color:var(--warn);margin-top:8px;
  display:none}

/* ---- review ---- */
.review-group{display:flex;flex-direction:column;gap:0}
.rv-row{display:flex;justify-content:space-between;align-items:center;
  padding:10px 0;border-bottom:1px solid var(--border);font-size:14px}
.rv-row:last-child{border-bottom:none}
.rv-key{color:var(--txt3);font-size:13px}
.rv-val{color:var(--txt);font-weight:500;text-align:right;word-break:break-all}

/* ---- done ---- */
.done-icon{font-size:52px;text-align:center}
.cmd-box{background:var(--card2);border:1px solid var(--border);border-radius:8px;
  padding:14px 16px;font-family:'Cascadia Code','Fira Mono','Consolas',monospace;
  font-size:13px;color:var(--ok);line-height:1.8;white-space:pre}

/* ---- footer ---- */
footer{position:fixed;bottom:0;left:0;right:0;padding:16px 32px;
  background:linear-gradient(to top,var(--bg) 70%,transparent);
  display:flex;align-items:center;gap:12px}
#btn-back{margin-right:auto}
.spacer{flex:1}

/* ---- spinner ---- */
@keyframes spin{to{transform:rotate(360deg)}}
.spin{display:inline-block;width:14px;height:14px;border:2px solid rgba(255,255,255,.3);
  border-top-color:#fff;border-radius:50%;animation:spin .7s linear infinite;vertical-align:middle}

/* ---- welcome hero ---- */
.hero{text-align:center;padding:12px 0 4px}
.hero-icon{font-size:48px;margin-bottom:12px}
.hero h1{font-size:26px;font-weight:800;margin-bottom:8px;
  background:linear-gradient(135deg,var(--accent),var(--accent2));
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
.hero p{color:var(--txt2);font-size:15px;max-width:440px;margin:0 auto;line-height:1.65}
.feature-list{display:flex;flex-direction:column;gap:8px;margin-top:4px}
.feat{display:flex;align-items:center;gap:10px;font-size:14px;color:var(--txt2)}
.feat .icon{font-size:18px;flex-shrink:0}

/* ---- tip box ---- */
.tip{background:var(--adim);border:1px solid rgba(129,140,248,.25);border-radius:8px;
  padding:12px 14px;font-size:13px;color:var(--txt2);line-height:1.55}
.tip b{color:var(--accent)}
</style>
</head>
<body>

<header>
  <div class="hrow">
    <div class="logo">deemix<span>-bulk</span></div>
    <div class="step-label" id="step-label"></div>
  </div>
  <div class="prog-track"><div class="prog-fill" id="prog-fill"></div></div>
</header>

<main>

<!-- ═══════════════ STEP 0 · WELCOME ═══════════════ -->
<div class="step active" id="step-0">
  <div class="card">
    <div class="hero">
      <div class="hero-icon">🎵</div>
      <h1>deemix-bulk Setup</h1>
      <p>Bulk-download your entire music library from Deezer and sync it to a NAS — automatically.</p>
    </div>
  </div>
  <div class="card">
    <h3>What you'll need</h3>
    <div class="feature-list" style="margin-top:12px">
      <div class="feat"><span class="icon">✅</span> <span>A <b>Deezer Premium</b> account (needed for FLAC)</span></div>
      <div class="feat"><span class="icon">✅</span> <span>The <b>deemix-gui server</b> .exe in this folder</span></div>
      <div class="feat"><span class="icon">⬜</span> <span>A NAS or network drive <i>(optional)</i></span></div>
      <div class="feat"><span class="icon">⬜</span> <span>An Ollama API key for AI disambiguation <i>(optional)</i></span></div>
    </div>
  </div>
  <div class="tip">This wizard will create <b>.env</b> and <b>artists.txt</b> in the project folder. Nothing is written until the final step.</div>
</div>

<!-- ═══════════════ STEP 1 · SERVER ═══════════════ -->
<div class="step" id="step-1">
  <div class="card">
    <div class="card-title">deemix-gui Server</div>
    <div class="card-sub">The download server must be running before we can verify your account. We'll start it automatically if we find the .exe.</div>
  </div>
  <div class="card" id="server-card">
    <div id="server-status-row" style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">
      <span id="server-badge" class="badge badge-warn"><span class="dot"></span> Checking…</span>
      <button class="btn-secondary btn-icon" onclick="checkServer()" id="btn-refresh-srv">⟳ Refresh</button>
      <button class="btn-primary btn-icon" onclick="startServer()" id="btn-start-srv" style="display:none">▶ Start Server</button>
    </div>
    <div id="srv-feedback" class="feedback"></div>
    <div id="exe-path" style="margin-top:12px;font-size:12px;color:var(--txt3)"></div>
  </div>
  <div class="tip"><b>Can't find the .exe?</b> Download the latest deemix-gui release from GitHub and put it in this folder, then click Refresh.</div>
</div>

<!-- ═══════════════ STEP 2 · DEEZER ACCOUNT ═══════════════ -->
<div class="step" id="step-2">
  <div class="card">
    <div class="card-title">Deezer Account</div>
    <div class="card-sub">You need a Deezer account to download music. <b>Deezer Premium</b> is required for FLAC quality — the free tier is MP3 only.</div>
  </div>
  <div class="card">
    <h3>Don't have an account yet?</h3>
    <p style="margin-bottom:14px">Create one at Deezer — it's free to sign up, then upgrade to Premium.</p>
    <button class="btn-secondary btn-icon full" onclick="window.open('https://www.deezer.com/register','_blank')">
      🌐 Open deezer.com/register
    </button>
  </div>
  <div class="tip" style="margin-top:4px">
    Already have an account? Just click <b>Continue</b> below.
  </div>
</div>

<!-- ═══════════════ STEP 3 · ARL TOKEN ═══════════════ -->
<div class="step" id="step-3">
  <div class="card">
    <div class="card-title">Deezer ARL Token</div>
    <div class="card-sub">The ARL is a session cookie that authenticates your downloads. It's tied to your account and rotates occasionally.</div>
  </div>
  <div class="card">
    <h3>How to get your ARL</h3>
    <div class="steps-list" style="margin-top:10px">
      <div class="s-item">
        <div class="s-num">1</div>
        <div class="s-text">Go to <a href="https://www.deezer.com" target="_blank">deezer.com</a> and log in to your account</div>
      </div>
      <div class="s-item">
        <div class="s-num">2</div>
        <div class="s-text">Press <kbd>F12</kbd> to open DevTools &nbsp;(Mac: <kbd>⌘</kbd> <kbd>⌥</kbd> <kbd>I</kbd>)</div>
      </div>
      <div class="s-item">
        <div class="s-num">3</div>
        <div class="s-text">Click the <kbd>Application</kbd> tab at the top of DevTools</div>
      </div>
      <div class="s-item">
        <div class="s-num">4</div>
        <div class="s-text">In the left sidebar: <b>Storage → Cookies → https://www.deezer.com</b></div>
      </div>
      <div class="s-item">
        <div class="s-num">5</div>
        <div class="s-text">Find the row named <b>arl</b>, double-click the Value cell, and copy the entire string</div>
      </div>
    </div>
  </div>
  <div class="card">
    <h3>Paste your ARL here</h3>
    <div class="show-hide" style="margin-top:8px">
      <input type="password" id="arl-input" placeholder="Paste your ARL token…" autocomplete="off">
      <button class="eye" onclick="toggleArl(this)" title="Show / hide">👁</button>
    </div>
    <div id="arl-feedback" class="feedback"></div>
    <div style="margin-top:14px;display:flex;gap:10px;flex-wrap:wrap">
      <button class="btn-primary btn-icon" onclick="verifyArl()" id="btn-verify-arl">🔑 Verify ARL</button>
      <button class="btn-ghost" onclick="skipArl()" id="btn-skip-arl">Skip for now</button>
    </div>
  </div>
</div>

<!-- ═══════════════ STEP 4 · QUALITY ═══════════════ -->
<div class="step" id="step-4">
  <div class="card">
    <div class="card-title">Download Quality</div>
    <div class="card-sub">Choose the audio format for your downloads. FLAC requires Deezer Premium.</div>
  </div>
  <div class="card">
    <h3 style="margin-bottom:12px">Format</h3>
    <div class="qual-grid">
      <div class="qual-card selected" id="q-flac" onclick="selectQuality('flac')">
        <span class="check">✓</span>
        <h4>FLAC</h4>
        <p>Lossless · ~30–50 MB/album track</p>
        <p style="margin-top:4px;color:var(--warn);font-size:11px">Requires Premium</p>
      </div>
      <div class="qual-card" id="q-mp3" onclick="selectQuality('mp3')">
        <span class="check">✓</span>
        <h4>MP3 320</h4>
        <p>High-quality lossy · ~10–15 MB</p>
        <p style="margin-top:4px;font-size:11px">Works with free tier</p>
      </div>
    </div>
  </div>
  <div class="card">
    <h3 style="margin-bottom:10px">Release types to download</h3>
    <div class="chip-row">
      <button class="chip on" id="chip-albums" onclick="toggleChip(this,'albums')">Albums</button>
      <button class="chip on" id="chip-eps" onclick="toggleChip(this,'eps')">EPs</button>
      <button class="chip" id="chip-singles" onclick="toggleChip(this,'singles')">Singles</button>
      <button class="chip" id="chip-compilations" onclick="toggleChip(this,'compilations')">Compilations</button>
    </div>
    <p style="margin-top:10px;font-size:12px">Singles can be a large volume of content.</p>
  </div>
</div>

<!-- ═══════════════ STEP 5 · NAS ═══════════════ -->
<div class="step" id="step-5">
  <div class="card">
    <div class="card-title">Network Drive (NAS)</div>
    <div class="card-sub">Automatically move completed artist folders to a NAS or shared drive over SMB. Skip if you only want local downloads.</div>
  </div>
  <div class="card">
    <label class="toggle-row" for="nas-toggle">
      <div>
        <div class="tlabel">Sync to NAS / network drive</div>
        <div class="tsub">Move finished bands to your music library automatically</div>
      </div>
      <div class="toggle"><input type="checkbox" id="nas-toggle" onchange="toggleNas(this)"><span class="tslider"></span></div>
    </label>
    <div class="opt-body hidden" id="nas-body">
      <div class="row2">
        <div class="field"><label>Host (IP or hostname)</label>
          <input type="text" id="nas-host" placeholder="192.168.1.100"></div>
        <div class="field"><label>Share name</label>
          <input type="text" id="nas-share" placeholder="data"></div>
      </div>
      <div class="row2">
        <div class="field"><label>Username</label>
          <input type="text" id="nas-user" placeholder="adam"></div>
        <div class="field"><label>Password</label>
          <div class="show-hide">
            <input type="password" id="nas-pass" placeholder="••••••••">
            <button class="eye" onclick="togglePw('nas-pass',this)">👁</button>
          </div>
        </div>
      </div>
      <div class="field"><label>Music path (relative to share root)</label>
        <input type="text" id="nas-path" placeholder="media/music" value="media/music"></div>
      <div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center">
        <button class="btn-secondary btn-icon" onclick="testNas()" id="btn-test-nas">🔌 Test Connection</button>
        <span id="nas-badge" style="display:none"></span>
      </div>
      <div id="nas-feedback" class="feedback"></div>
    </div>
  </div>
</div>

<!-- ═══════════════ STEP 6 · AI ═══════════════ -->
<div class="step" id="step-6">
  <div class="card">
    <div class="card-title">AI Artist Disambiguation</div>
    <div class="card-sub">When a search returns multiple artists with the same name, an LLM picks the right one. Uses <b>Ollama cloud</b> — only called for ambiguous cases.</div>
  </div>
  <div class="card">
    <label class="toggle-row" for="ai-toggle">
      <div>
        <div class="tlabel">Enable AI disambiguation</div>
        <div class="tsub">Prevents wrong-artist downloads for common/shared names</div>
      </div>
      <div class="toggle"><input type="checkbox" id="ai-toggle" onchange="toggleAi(this)"><span class="tslider"></span></div>
    </label>
    <div class="opt-body hidden" id="ai-body">
      <div class="field">
        <label>Ollama API Key &nbsp;—&nbsp; <a href="https://ollama.com" target="_blank" style="color:var(--accent);font-size:12px">get one at ollama.com</a></label>
        <div class="show-hide">
          <input type="password" id="ollama-key" placeholder="Paste your Ollama API key…" autocomplete="off">
          <button class="eye" onclick="togglePw('ollama-key',this)">👁</button>
        </div>
      </div>
      <div class="field">
        <label>Model</label>
        <select id="ollama-model">
          <option value="gemini-3-flash-preview">gemini-3-flash-preview (recommended — fast &amp; cheap)</option>
          <option value="llama3.3">llama3.3</option>
          <option value="mistral">mistral</option>
        </select>
      </div>
    </div>
  </div>
  <div class="tip">You can skip this and use <code style="font-size:12px;color:var(--accent)">resolve_check.py</code> separately to audit your list first.</div>
</div>

<!-- ═══════════════ STEP 7 · ARTISTS ═══════════════ -->
<div class="step" id="step-7">
  <div class="card">
    <div class="card-title">Your Artist List</div>
    <div class="card-sub">One entry per line. You can use artist names, Deezer IDs, or Deezer artist URLs. Blank lines and lines starting with # are ignored.</div>
  </div>
  <div class="card">
    <textarea id="artist-textarea"
      placeholder="Metallica&#10;Tool&#10;Pantera&#10;9140&#10;https://www.deezer.com/artist/9140&#10;&#10;# you can add comments too"
      oninput="artistsChanged()"></textarea>
    <div class="artist-counter" id="artist-counter">0 artists</div>
    <div class="dup-warn" id="dup-warn"></div>
    <div class="artist-tags" id="artist-tags"></div>
  </div>
  <div class="tip"><b>Tip:</b> Paste a comma-separated or newline-separated list — the wizard normalises it. You can also run <b>resolve_check.py --ai</b> afterwards to audit any ambiguous names before downloading.</div>
</div>

<!-- ═══════════════ STEP 8 · REVIEW ═══════════════ -->
<div class="step" id="step-8">
  <div class="card">
    <div class="card-title">Review &amp; Save</div>
    <div class="card-sub">Everything looks good? Click <b>Save &amp; Finish</b> to write <code>.env</code> and <code>artists.txt</code>.</div>
  </div>
  <div class="card" id="review-card">
    <div class="review-group" id="review-rows"></div>
  </div>
  <div id="save-feedback" class="feedback"></div>
</div>

<!-- ═══════════════ STEP 9 · DONE ═══════════════ -->
<div class="step" id="step-9">
  <div class="card">
    <div class="done-icon" style="margin-bottom:12px">🎉</div>
    <h2 style="text-align:center;margin-bottom:8px">You're all set!</h2>
    <p style="text-align:center"><code>.env</code> and <code>artists.txt</code> have been written. Run these commands to start downloading:</p>
  </div>
  <div class="card">
    <h3 style="margin-bottom:10px">Phase 1 — Queue downloads</h3>
    <div class="cmd-box" id="cmd-dl">python deemix_dl.py --albums --eps --flac</div>
  </div>
  <div class="card" id="cmd-sync-card">
    <h3 style="margin-bottom:10px">Phase 2 — Move to NAS when done</h3>
    <div class="cmd-box">python deemix_sync.py --prune-artists</div>
  </div>
  <div class="card">
    <h3 style="margin-bottom:10px">Optional — Audit artist names first</h3>
    <div class="cmd-box">python resolve_check.py --ai</div>
  </div>
  <button class="btn-ghost full" onclick="api('/api/shutdown',{}).then(()=>window.close())"
    style="margin-top:4px">Close this wizard</button>
</div>

</main>

<footer>
  <button class="btn-ghost btn-icon" id="btn-back" onclick="back()">← Back</button>
  <div class="spacer"></div>
  <button class="btn-primary btn-icon" id="btn-next" onclick="next()">Continue →</button>
</footer>

<script>
// ─── State ───────────────────────────────────────────────────────────────────
const W = {
  step: 0,
  totalVisible: 9, // steps 0–8 shown in progress (9 = done)
  config: {
    DEEMIX_SERVER: 'http://127.0.0.1:6595',
    DEEMIX_QUALITY: 'flac',
    DEEMIX_ARL: '',
    NAS_HOST:'', NAS_SHARE:'', NAS_USER:'', NAS_PASS:'',
    NAS_MUSIC_PATH: 'media/music',
    OLLAMA_API_KEY:'', OLLAMA_MODEL:'gemini-3-flash-preview',
  },
  releases: { albums:true, eps:true, singles:false, compilations:false },
  artists: [],
  serverOk: false,
  arlOk: false,
  arlSkipped: false,
  nasEnabled: false,
  nasOk: false,
  aiEnabled: false,
  exePath: null,
};

// ─── Navigation ──────────────────────────────────────────────────────────────
function goto(n) {
  document.getElementById('step-' + W.step).classList.remove('active');
  W.step = n;
  document.getElementById('step-' + W.step).classList.add('active');
  updateChrome();
  window.scrollTo(0,0);
}

function updateChrome() {
  const s = W.step;
  const pct = s === 9 ? 100 : Math.round((s / W.totalVisible) * 100);
  document.getElementById('prog-fill').style.width = pct + '%';
  document.getElementById('step-label').textContent =
    s === 9 ? 'Complete!' : `Step ${s + 1} of ${W.totalVisible + 1}`;

  const bb = document.getElementById('btn-back');
  const bn = document.getElementById('btn-next');
  bb.style.display = s === 0 ? 'none' : '';
  bn.style.display = s === 9 ? 'none' : '';

  if (s === 8) {
    bn.textContent = '💾 Save & Finish';
    bn.className = 'btn-primary btn-icon';
  } else {
    bn.textContent = 'Continue →';
  }
}

async function next() {
  if (!await validate(W.step)) return;

  // collect step data before leaving
  collect(W.step);

  if (W.step === 8) { await save(); return; }
  goto(W.step + 1);
  // run side-effects on enter
  onEnter(W.step);
}

function back() {
  if (W.step === 0) return;
  collect(W.step);
  goto(W.step - 1);
}

// ─── Validate ────────────────────────────────────────────────────────────────
async function validate(s) {
  if (s === 1) {
    if (!W.serverOk) { flash('srv-feedback','error','Start the server (or click Refresh) before continuing.'); return false; }
  }
  if (s === 3) {
    if (!W.arlOk && !W.arlSkipped) { flash('arl-feedback','error','Please verify your ARL (or click "Skip for now").'); return false; }
  }
  if (s === 7) {
    W.artists = parseArtists(document.getElementById('artist-textarea').value);
    if (W.artists.length === 0) { alert('Add at least one artist before continuing.'); return false; }
  }
  return true;
}

// ─── Collect form data ───────────────────────────────────────────────────────
function collect(s) {
  if (s === 3) { W.config.DEEMIX_ARL = v('arl-input'); }
  if (s === 5 && W.nasEnabled) {
    W.config.NAS_HOST  = v('nas-host');
    W.config.NAS_SHARE = v('nas-share');
    W.config.NAS_USER  = v('nas-user');
    W.config.NAS_PASS  = v('nas-pass');
    W.config.NAS_MUSIC_PATH = v('nas-path') || 'media/music';
  } else if (s === 5) {
    W.config.NAS_HOST = '';
  }
  if (s === 6 && W.aiEnabled) {
    W.config.OLLAMA_API_KEY = v('ollama-key');
    W.config.OLLAMA_MODEL   = v('ollama-model');
  } else if (s === 6) {
    W.config.OLLAMA_API_KEY = '';
  }
  if (s === 7) {
    W.artists = parseArtists(document.getElementById('artist-textarea').value);
  }
}

function v(id) { return (document.getElementById(id)||{}).value || ''; }

// ─── On-enter side effects ────────────────────────────────────────────────────
function onEnter(s) {
  if (s === 1) checkServer();
  if (s === 8) buildReview();
}

// ─── Server step ─────────────────────────────────────────────────────────────
async function checkServer() {
  setBadge('server-badge','warn','Checking…');
  document.getElementById('srv-feedback').className='feedback';
  const res = await api('/api/check-server', {server: W.config.DEEMIX_SERVER});
  if (res.running) {
    setBadge('server-badge','ok','Server running ✓');
    W.serverOk = true;
    document.getElementById('btn-start-srv').style.display='none';
  } else {
    setBadge('server-badge','err','Not running');
    W.serverOk = false;
    const btnStart = document.getElementById('btn-start-srv');
    if (W.exePath) btnStart.style.display='';
  }
}

async function startServer() {
  const btn = document.getElementById('btn-start-srv');
  btn.disabled = true;
  btn.innerHTML = '<span class="spin"></span> Starting…';
  const res = await api('/api/start-server', {exe: W.exePath, server: W.config.DEEMIX_SERVER});
  btn.disabled = false;
  btn.innerHTML = '▶ Start Server';
  if (res.ok) {
    setBadge('server-badge','ok','Server running ✓');
    W.serverOk = true;
    btn.style.display='none';
    flash('srv-feedback','ok','Server started successfully.');
  } else {
    flash('srv-feedback','error', res.error || 'Failed to start server.');
  }
}

// ─── ARL step ────────────────────────────────────────────────────────────────
async function verifyArl() {
  const arl = v('arl-input').trim();
  if (!arl) { flash('arl-feedback','error','Paste your ARL first.'); return; }
  const btn = document.getElementById('btn-verify-arl');
  btn.disabled=true; btn.innerHTML='<span class="spin"></span> Verifying…';
  const res = await api('/api/verify-arl', {arl, server: W.config.DEEMIX_SERVER});
  btn.disabled=false; btn.innerHTML='🔑 Verify ARL';
  if (res.ok) {
    W.arlOk=true; W.config.DEEMIX_ARL=arl;
    flash('arl-feedback','ok', `Logged in as: ${res.name} ✓`);
  } else {
    W.arlOk=false;
    flash('arl-feedback','error', res.error || 'Verification failed.');
  }
}

function skipArl() { W.arlSkipped=true; goto(W.step+1); onEnter(W.step); }

function toggleArl(btn) {
  const inp = document.getElementById('arl-input');
  inp.type = inp.type==='password'?'text':'password';
}

// ─── Quality step ────────────────────────────────────────────────────────────
function selectQuality(q) {
  W.config.DEEMIX_QUALITY = q;
  document.getElementById('q-flac').className = 'qual-card' + (q==='flac'?' selected':'');
  document.getElementById('q-mp3').className  = 'qual-card' + (q==='mp3' ?' selected':'');
}

function toggleChip(el, key) {
  W.releases[key] = !W.releases[key];
  el.className = 'chip' + (W.releases[key]?' on':'');
}

// ─── NAS step ────────────────────────────────────────────────────────────────
function toggleNas(cb) {
  W.nasEnabled = cb.checked;
  document.getElementById('nas-body').className = 'opt-body' + (W.nasEnabled?'':' hidden');
}

async function testNas() {
  const btn = document.getElementById('btn-test-nas');
  btn.disabled=true; btn.innerHTML='<span class="spin"></span> Testing…';
  const res = await api('/api/test-nas', {
    host: v('nas-host'), share: v('nas-share'),
    user: v('nas-user'), password: v('nas-pass')
  });
  btn.disabled=false; btn.innerHTML='🔌 Test Connection';
  const badge = document.getElementById('nas-badge');
  badge.style.display='';
  if (res.ok) {
    badge.className='badge badge-ok'; badge.innerHTML='<span class="dot"></span> Connected ✓';
    W.nasOk=true; flash('nas-feedback','ok','Connection successful!');
  } else {
    badge.className='badge badge-err'; badge.innerHTML='<span class="dot"></span> Failed';
    W.nasOk=false; flash('nas-feedback','error', res.error||'Connection failed.');
  }
}

// ─── AI step ─────────────────────────────────────────────────────────────────
function toggleAi(cb) {
  W.aiEnabled = cb.checked;
  document.getElementById('ai-body').className = 'opt-body' + (W.aiEnabled?'':' hidden');
}

// ─── Artists step ─────────────────────────────────────────────────────────────
function parseArtists(raw) {
  // normalise commas and semicolons to newlines, then split
  const lines = raw.replace(/[;,]/g, '\n').split('\n');
  const out = [];
  for (const line of lines) {
    const s = line.trim();
    if (!s || s.startsWith('#')) continue;
    out.push(s);
  }
  return out;
}

function artistsChanged() {
  const artists = parseArtists(document.getElementById('artist-textarea').value);
  const counter = document.getElementById('artist-counter');
  counter.textContent = artists.length + (artists.length===1?' artist':' artists');

  // duplicate detection
  const lower = artists.map(a=>a.toLowerCase());
  const dups = lower.filter((a,i)=>lower.indexOf(a)!==i);
  const dupWarn = document.getElementById('dup-warn');
  if (dups.length) {
    dupWarn.style.display='block';
    dupWarn.textContent = '⚠ Possible duplicates: ' + [...new Set(dups)].join(', ');
  } else {
    dupWarn.style.display='none';
  }

  // preview tags
  const container = document.getElementById('artist-tags');
  container.innerHTML='';
  const preview = artists.slice(0,30);
  preview.forEach(a=>{
    const tag=document.createElement('span');
    tag.className='atag'; tag.textContent=a;
    container.appendChild(tag);
  });
  if (artists.length>30) {
    const more=document.createElement('span');
    more.className='atag'; more.style.color='var(--txt3)';
    more.textContent=`+ ${artists.length-30} more`;
    container.appendChild(more);
  }
}

// ─── Review step ─────────────────────────────────────────────────────────────
function buildReview() {
  collect(7); // ensure latest artists
  const rows = [];
  const arl = W.config.DEEMIX_ARL;
  const arlDisplay = arl ? arl.slice(0,10)+'…' : '(not set — will need to add to .env manually)';
  const types = Object.entries(W.releases).filter(([,v])=>v).map(([k])=>k).join(', ');

  rows.push(['ARL', arlDisplay]);
  rows.push(['Quality', W.config.DEEMIX_QUALITY.toUpperCase()]);
  rows.push(['Release types', types || 'none selected']);
  rows.push(['Artists', W.artists.length + ' entries']);

  if (W.nasEnabled && W.config.NAS_HOST) {
    rows.push(['NAS host', W.config.NAS_HOST]);
    rows.push(['NAS share', `\\\\${W.config.NAS_HOST}\\${W.config.NAS_SHARE}\\${W.config.NAS_MUSIC_PATH}`]);
    rows.push(['NAS user', W.config.NAS_USER]);
    rows.push(['NAS password', '••••••••']);
  } else {
    rows.push(['NAS sync', 'Disabled (local downloads only)']);
  }

  if (W.aiEnabled && W.config.OLLAMA_API_KEY) {
    rows.push(['AI model', W.config.OLLAMA_MODEL]);
    rows.push(['Ollama key', W.config.OLLAMA_API_KEY.slice(0,8)+'…']);
  } else {
    rows.push(['AI disambiguation', 'Disabled']);
  }

  const container = document.getElementById('review-rows');
  container.innerHTML = rows.map(([k,vv])=>`
    <div class="rv-row">
      <span class="rv-key">${k}</span>
      <span class="rv-val">${vv}</span>
    </div>`).join('');

  // build done-step commands
  const types2 = Object.entries(W.releases).filter(([,v])=>v).map(([k])=>'--'+k.replace('compilations','compilations')).join(' ');
  const qual = '--' + W.config.DEEMIX_QUALITY;
  document.getElementById('cmd-dl').textContent = `python deemix_dl.py ${types2} ${qual}`.trim();
  document.getElementById('cmd-sync-card').style.display = W.nasEnabled ? '' : 'none';
}

// ─── Save ─────────────────────────────────────────────────────────────────────
async function save() {
  const btn = document.getElementById('btn-next');
  btn.disabled=true; btn.innerHTML='<span class="spin"></span> Saving…';

  const cfg = {...W.config};
  if (!W.nasEnabled) cfg.NAS_HOST='';
  if (!W.aiEnabled)  cfg.OLLAMA_API_KEY='';

  const res = await api('/api/save', {config: cfg, artists: W.artists});
  btn.disabled=false; btn.innerHTML='💾 Save & Finish';
  if (res.ok) {
    goto(9);
  } else {
    flash('save-feedback','error', res.error||'Save failed.');
  }
}

// ─── Utils ───────────────────────────────────────────────────────────────────
async function api(path, body) {
  try {
    const r = await fetch(path, {
      method:'POST', headers:{'Content-Type':'application/json'},
      body: JSON.stringify(body)
    });
    return r.json();
  } catch(e) {
    return {ok:false, error: e.message};
  }
}

function flash(id, type, msg) {
  const el = document.getElementById(id);
  if (!el) return;
  el.className = 'feedback ' + (type==='ok'?'ok':type==='error'?'err':'info');
  el.textContent = msg;
}

function setBadge(id, type, text) {
  const el = document.getElementById(id);
  if (!el) return;
  el.className = `badge badge-${type}`;
  el.innerHTML = `<span class="dot"></span> ${text}`;
}

function togglePw(inputId, btn) {
  const inp = document.getElementById(inputId);
  inp.type = inp.type==='password'?'text':'password';
}

// ─── Init ─────────────────────────────────────────────────────────────────────
async function init() {
  updateChrome();
  const status = await fetch('/api/status').then(r=>r.json()).catch(()=>({}));

  W.exePath = status.exePath || null;
  if (W.exePath) {
    const el = document.getElementById('exe-path');
    if (el) el.textContent = 'Found: ' + W.exePath;
  }

  // Pre-fill from existing .env
  const env = status.env || {};
  if (env.DEEMIX_ARL)       { W.config.DEEMIX_ARL=env.DEEMIX_ARL; document.getElementById('arl-input').value=env.DEEMIX_ARL; }
  if (env.DEEMIX_SERVER)    { W.config.DEEMIX_SERVER=env.DEEMIX_SERVER; }
  if (env.DEEMIX_QUALITY)   { selectQuality(env.DEEMIX_QUALITY); }
  if (env.NAS_HOST)         { document.getElementById('nas-toggle').checked=true; toggleNas({checked:true}); document.getElementById('nas-host').value=env.NAS_HOST; W.nasEnabled=true; }
  if (env.NAS_SHARE)        document.getElementById('nas-share').value=env.NAS_SHARE;
  if (env.NAS_USER)         document.getElementById('nas-user').value=env.NAS_USER;
  if (env.NAS_PASS)         document.getElementById('nas-pass').value=env.NAS_PASS;
  if (env.NAS_MUSIC_PATH)   document.getElementById('nas-path').value=env.NAS_MUSIC_PATH;
  if (env.OLLAMA_API_KEY)   { document.getElementById('ai-toggle').checked=true; toggleAi({checked:true}); document.getElementById('ollama-key').value=env.OLLAMA_API_KEY; W.aiEnabled=true; }
  if (env.OLLAMA_MODEL)     document.getElementById('ollama-model').value=env.OLLAMA_MODEL;

  // Pre-fill artists
  const artists = status.artists || [];
  if (artists.length) {
    document.getElementById('artist-textarea').value = artists.join('\n');
    artistsChanged();
  }

  // Check if server is already running
  if (status.serverRunning) {
    W.serverOk = true;
  }
}

init();
</script>
</body>
</html>
"""


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main():
    url = f"http://{HOST}:{PORT}"
    server = http.server.ThreadingHTTPServer((HOST, PORT), WizardHandler)
    print(f"\n  deemix-bulk Setup Wizard")
    print(f"  ─────────────────────────────")
    print(f"  Opening: {url}")
    print(f"  Press Ctrl+C to exit\n")
    threading.Timer(0.6, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    print("\n  Wizard closed.")


if __name__ == "__main__":
    main()
